---
- name: Configure machine with Docker, Minikube, and kubectl
  hosts: all
  become: yes

  tasks:
    - name: Update APT cache
      apt:
        update_cache: yes

    - name: Install prerequisite packages
      apt:
        name:
          - ca-certificates
          - curl
          - gnupg
          - lsb-release
          - wget
          - apt-transport-https
        state: present

    - name: Add Docker APT repository GPG key directly to apt keyring
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker APT repository
      apt_repository:
        repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_lsb.codename }} stable"
        state: present
        filename: docker

    - name: Update apt cache
      apt:
        update_cache: yes


    - name: Update APT cache after adding Docker repo
      apt:
        update_cache: yes

    - name: Install Docker packages
      apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
        state: present

    - name: Add current user to Docker group
      user:
        name: "{{ ansible_user }}"
        groups: docker
        append: yes

    - name: Download Minikube
      get_url:
        url: https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
        dest: /tmp/minikube
        mode: '0755'

    - name: Install Minikube
      copy:
        src: /tmp/minikube
        dest: /usr/local/bin/minikube
        remote_src: yes
        mode: '0755'

    - name: Download kubectl binary
      shell: |
        curl -LO https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl
      args:
        chdir: /tmp

    - name: Install kubectl
      copy:
        src: /tmp/kubectl
        dest: /usr/local/bin/kubectl
        mode: '0755'
        remote_src: yes

    - name: Ensure Docker service is started
      service:
        name: docker
        state: started
        enabled: yes

    - name: Reconnect SSH session to apply new Docker group membership
      meta: reset_connection

    - name: Start Minikube with Docker driver
      become_user: "{{ ansible_user }}"
      shell: minikube start --driver=docker
      environment:
        CHANGE_MINIKUBE_NONE_USER: "true"

    